name: IITGMaps

services: 
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - server
